language: node_js

cache:
  directories:
  - $HOME/.npm
  - $HOME/.yarn-cache
  - node_modules

before_install:
- mv .travis.npmrc .npmrc
- npm i -g yarn --cache-min 999999999

install:
- yarn

script:
- yarn run lint && yarn run test
